import type { BlogType, Section } from "./types";

export function generateLayoutTemplate(
  type: BlogType,
): Omit<Section, "notes">[] {
  const templates: Record<BlogType, Omit<Section, "notes">[]> = {
    troubleshooting: [
      {
        id: "problem",
        title: "문제 상황",
        level: "h2",
        purpose: "독자가 어떤 문제인지 즉시 파악할 수 있도록 문제 정의",
        requiredInfo: ["서비스/시스템 환경", "발생 시점/조건", "증상 요약"],
        recommendedImages: ["아키텍처 다이어그램"],
        status: "pending",
      },
      {
        id: "environment",
        title: "환경 및 전제 조건",
        level: "h3",
        purpose: "재현에 필요한 환경 정보 명시",
        requiredInfo: ["OS/버전", "배포 방식", "관련 의존성"],
        status: "pending",
        parentId: "problem",
      },
      {
        id: "symptoms",
        title: "증상 및 로그",
        level: "h2",
        purpose: "구체적인 에러 메시지와 로그 기록",
        requiredInfo: ["에러 메시지", "스택 트레이스", "발생 빈도/패턴"],
        recommendedImages: ["에러 로그 스크린샷"],
        status: "pending",
      },
      {
        id: "analysis",
        title: "원인 분석",
        level: "h2",
        purpose: "가설 수립과 검증 과정 설명",
        requiredInfo: ["초기 가설", "검증 방법", "실제 원인"],
        status: "pending",
      },
      {
        id: "solution",
        title: "해결 방법",
        level: "h2",
        purpose: "적용한 해결책과 결과",
        requiredInfo: ["해결 코드/설정", "적용 결과", "부작용 여부"],
        recommendedImages: ["코드 diff", "결과 스크린샷"],
        status: "pending",
      },
      {
        id: "retrospective",
        title: "회고 및 재발 방지",
        level: "h2",
        purpose: "배운 점과 예방 조치",
        requiredInfo: ["핵심 교훈", "재발 방지 조치", "참고 자료"],
        status: "pending",
      },
    ],
    design: [
      {
        id: "background",
        title: "배경 및 목표",
        level: "h2",
        purpose: "왜 이 기능이 필요한지 설명",
        requiredInfo: ["비즈니스 요구사항", "기술적 목표", "성공 기준"],
        status: "pending",
      },
      {
        id: "requirements",
        title: "요구사항 분석",
        level: "h2",
        purpose: "기능/비기능 요구사항 정리",
        requiredInfo: ["기능 요구사항", "비기능 요구사항", "제약 조건"],
        status: "pending",
      },
      {
        id: "design-decision",
        title: "설계 결정",
        level: "h2",
        purpose: "핵심 설계 결정과 그 이유",
        requiredInfo: ["고려한 대안들", "선택한 방식", "선택 근거"],
        recommendedImages: ["설계 다이어그램", "시퀀스 다이어그램"],
        status: "pending",
      },
      {
        id: "implementation",
        title: "구현 상세",
        level: "h2",
        purpose: "실제 구현 코드와 설명",
        requiredInfo: ["핵심 코드", "구현 순서", "주의점"],
        recommendedImages: ["코드 스니펫"],
        status: "pending",
      },
      {
        id: "result",
        title: "결과 및 개선점",
        level: "h2",
        purpose: "구현 결과와 향후 계획",
        requiredInfo: ["달성 결과", "남은 과제", "향후 개선 방향"],
        status: "pending",
      },
    ],
    analysis: [
      {
        id: "objective",
        title: "분석 목적",
        level: "h2",
        purpose: "왜 이 분석이 필요한지",
        requiredInfo: ["비즈니스 질문", "분석 목표", "기대 결과"],
        status: "pending",
      },
      {
        id: "methodology",
        title: "분석 방법론",
        level: "h2",
        purpose: "어떻게 분석했는지",
        requiredInfo: ["데이터 소스", "분석 기간", "사용 도구/방법"],
        status: "pending",
      },
      {
        id: "findings",
        title: "주요 발견",
        level: "h2",
        purpose: "분석 결과 핵심 인사이트",
        requiredInfo: ["주요 지표", "패턴/트렌드", "이상치/특이점"],
        recommendedImages: ["차트", "대시보드 스크린샷"],
        status: "pending",
      },
      {
        id: "interpretation",
        title: "해석 및 시사점",
        level: "h2",
        purpose: "결과가 의미하는 바",
        requiredInfo: ["비즈니스 의미", "가설 검증 결과", "추가 분석 필요성"],
        status: "pending",
      },
      {
        id: "action",
        title: "액션 아이템",
        level: "h2",
        purpose: "다음 단계 제안",
        requiredInfo: ["권장 조치", "우선순위", "예상 효과"],
        status: "pending",
      },
    ],
    learning: [
      {
        id: "overview",
        title: "개요",
        level: "h2",
        purpose: "학습 자료 소개",
        requiredInfo: ["자료 출처", "저자/발표자", "핵심 주제"],
        status: "pending",
      },
      {
        id: "key-concepts",
        title: "핵심 개념",
        level: "h2",
        purpose: "중요 개념 정리",
        requiredInfo: ["주요 용어", "핵심 아이디어", "관련 배경지식"],
        recommendedImages: ["개념 다이어그램"],
        status: "pending",
      },
      {
        id: "details",
        title: "상세 내용",
        level: "h2",
        purpose: "깊이 있는 내용 정리",
        requiredInfo: ["세부 설명", "예시/사례", "수식/알고리즘(해당시)"],
        status: "pending",
      },
      {
        id: "thoughts",
        title: "개인 생각",
        level: "h2",
        purpose: "내 관점과 의견",
        requiredInfo: ["인상 깊은 점", "의문점", "실무 적용 가능성"],
        status: "pending",
      },
      {
        id: "summary",
        title: "정리",
        level: "h2",
        purpose: "핵심 요약과 참고자료",
        requiredInfo: ["한줄 요약", "추천 대상", "관련 자료 링크"],
        status: "pending",
      },
    ],
  };

  return templates[type];
}
